### PR TITLE
Add students to student tab with backend support (#105)

### PR DESCRIPTION
**Pull request by willji0023**
### Administrative Info

Make sure your branch name conforms to: `<feature/staging/hotfix/...>/[username]/[Github Issue]-[3-4 word description separated by dashes]`.

### What issue(s) does this branch close?

#105 

### Changes
What changes did you make?

- Added a backend route to `/students` to pull a list of all students (without repeats) and connected students tab front end to route
- Added filtering and ordering functionality to students tab

### Testing

How did you confirm your changes worked?

- `npm run dev`
- Create students objects in the database
- Check that student cards appear for each student object, and they are able to be searched, ordered, and filtered.

### Confirmation of Change

Upload a screenshot, if possible. Otherwise, please provide instructions on how to see the change.

| Students Tab with Dummy Students without Levels |
| ----------------------- |
| image |

### CODE REVIEW

**Review by Anshul-Birla — CHANGES_REQUESTED** [review]
Some minor changes required, but good work :)

**Review by Anshul-Birla — COMMENTED** [review]
Also, can you write some tests for the new API route? Just want to make sure things will work in the future if something gets changed

**Comment by willji0023** [comment]
> Also, can you write some tests for the new API route? Just want to make sure things will work in the future if something gets changed

Added and addressed your other comments in new iteration

**Review by Anshul-Birla — APPROVED** [review]
Love it :). Great work

**Pull request merged**
